apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.config }}
  {{- range $key, $value := .Values.config }}
    {{- $key | trim | nindent 2 }}: | 
    {{- $value | trim | nindent 4 }}
  {{- end }}
{{- else }}
{{- end }}
  