apiVersion: v2
name: newrelic-infra-k8s-singleton
description: Installs the New Relic Infrastructure agent as a Kubernetes singleton deployment

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "3.2.24"

dependencies:
  - name: common-library
    version: 1.1.1
    repository: "https://helm-charts.newrelic.com"

keywords:
  - newrelic
  - chart-library
  - kubernetes
  - infrastructure

maintainers:
  - name: Max Lemieux
    url: https://github.com/maxlemieux
  - name: Brad Schmitt
    url: https://github.com/bpschmitt
 
