licenseKey: ""
cluster: ""
clusternamehack: '{"clusterName": ""}'
customSecretName: ""
customSecretLicenseKey: ""

nameOverride: ""
fullnameOverride: ""

image:
  registry:
  repository: newrelic/infrastructure-bundle
  pullPolicy: IfNotPresent
  tag: "3.2.24"

imagePullSecrets: []

config:
  nri-flex.yaml: |
    integrations:
    - name: nri-flex
      # interval: 30s
      config:
        name: pingFlex
        apis:
          - name: ping
            commands:
              - name: google
                run: ping -c 5 google.com || true
                split_output: statistics ---
                regex_matches:
                  - expression: ([0-9]+\.?[0-9]+)\/([0-9]+\.?[0-9]+)\/([0-9]+\.?[0-9]+)
                    keys: [min, avg, max]
                    ### there are two different variants for the packet statistics returned, below allows support for both
                  - expression: (\d+) packets transmitted, (\d+) packets received, (\S+)% packet loss
                    keys: [packetsTransmitted, packetsReceived, packetLoss]
                  - expression: (\d+) packets transmitted, (\d+) received, (\d+)% packet loss, time (\d+)
                    keys:
                      [packetsTransmitted, packetsReceived, packetLoss, timeMs]
            custom_attributes:
              url: google.com
  # nri-mysql.yaml: |
  #   integrations:
  #     - name: nri-mysql
  #       env:
  #         # Using the discovered IP as the host address
  #         HOSTNAME: your-hostname
  #         PORT: 3306
  #         # ENABLE_TLS: false
  #         # INSECURE_SKIP_VERIFY: false
  #         # Specify extra connection parameters as attr1=val1&attr2=val2.
  #         # EXTRA_CONNECTION_URL_ARGS: ""

  #         # If not empty `socket` parameter will discard `port` parameter
  #         # SOCKET: <PATH_TO_LOCAL_SOCKET_FILE_NAME>
  #         USERNAME: user123
  #         PASSWORD: password123
  #         # Allow old password https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_old_passwords
  #         # OLD_PASSWORDS: false

  #         # Name of the database to be monitored
  #         DATABASE: my_db

  #         # Enable extended metrics
  #         # EXTENDED_METRICS: false

  #         # Enable additional metrics
  #         # EXTENDED_INNODB_METRICS: false
  #         # EXTENDED_MY_ISAM_METRICS: false

  #         # New users should leave this property as `true`, to identify the
  #         # monitored entities as `remote`. Setting this property to `false` (the
  #         # default value) is deprecated and will be removed soon, disallowing
  #         # entities that are identified as `local`.
  #         # Please check the documentation to get more information about local
  #         # versus remote entities:
  #         # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
  #         REMOTE_MONITORING: true
  #       labels:
  #         owner: your_name


serviceAccount:
  create:
  annotations:
  name:

deploymentAnnotations: {}
podAnnotations: {}
labels: {}
podLabels: {}

##########################################################
# DO NOT USE: Not working, not tested, or not applicable #
##########################################################
privileged:
priorityClassName: ""
hostNetwork:
podSecurityContext: {}
  # fsGroup: 2000
containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

dnsconfig: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

proxy:

lowDataMode:

nrStaging:
fedRamp:
  enabled:

verboseLog:
##########################################################
# End of DO NOT USE                                      #
##########################################################